name: Databricks Update

on:
  workflow_dispatch:
    inputs:
      databricks_job_name:
        description: 'Name of the Databricks job'
        required: true
        type: string

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run IMERG
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/update_imerg.py