name: Databricks Update

on:
  workflow_dispatch:
    inputs:
      databricks_job_name:
        description: 'Name of the Databricks job'
        required: true
        type: string

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install as package
      run: pip install -e .

    - name: Display inputs
      run: echo "Run triggered by ${{ inputs.databricks_job_name }}"

    - name: Trigger IMERG updates
      if: inputs.databricks_job_name == 'imerg'
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/imerg.py

    - name: Trigger SEAS5 updates
      if: inputs.databricks_job_name == 'seas5'
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/seas5.py

    - name: Trigger Floodscan updates
      if: inputs.databricks_job_name == 'floodscan'
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/floodscan.py

    - name: Trigger ERA5 updates
      if: inputs.databricks_job_name == 'era5'
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/era5.py