name: Hello World

on:
  workflow_dispatch:
    inputs:
      databricks_job_name:
        description: 'Name of the Databricks job'
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use job name
      run: echo "${{ inputs.databricks_job_name }} just ran!"