name: Databricks Update

on:
  workflow_dispatch:
    inputs:
      databricks_job_name:
        description: 'Name of the Databricks job'
        required: true
        type: string

jobs:
  send-update:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install as package
      run: pip install -e .

    - name: Run IMERG
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python updates/imerg.py