name: Hello World

on:
  workflow_dispatch:
    inputs:
      databricks_job_name:
        description: 'Name of the Databricks job'
        required: true
        type: string
      databricks_job_id:
        description: 'Databricks job ID'
        required: true

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use job name
      run: |
        echo "The Databricks job name is ${{ inputs.databricks_job_name }}" \
          echo "The Databricks job id is ${{ inputs.databricks_job_id }}"